---
title: "Progress Memo 1"
subtitle: |
  | Final Project 
  | Data Science 2 with R (STAT 301-2)
author: "Donny Tou"
date: today

format:
  html:
    toc: true
    embed-resources: true
    
execute:
  echo: false
  warning: false

from: markdown+emoji 
reference-location: margin
citation-location: margin
---

::: {.callout-important}
## Memo format

Like all other submissions for this course, we expect the memo to be neat and well organized. This a template to get you started. 

You should make this document your own. To help with this we have added a date to the yaml above (good whenever writing memos). You should remove this block when making this document your own.

:::

::: {.callout-tip icon=false}

## Github Repo Link

[Donny's Final Project Repo](https://github.com/stat301-2-2024-winter/final-project-2-donnytou.git)

:::

## Prediction Problem
Describe your prediction research question/objective and identify the type of prediction problem it is. This includes identifying a variable and clearly stating if it is a classification or regression problem. Provide a motivation for pursuing this particular problem: Why would having a prediction model be useful for this problem? Why is it interesting to you? Is this part of a larger research project? Just thought it would be fun? etc.

## Data Source

Identify and describe your data source or sources -- citations would be appropriate. Citations must include links to the data source(s).

Blah blah blah^[[Hotel Booking Dataset — Kaggle](https://www.kaggle.com/datasets/jessemostipak/hotel-booking-demand)]

Hi^[[Antonio, N., de Almeida, A., & Nunes, L. (2019). Hotel booking demand datasets. Data in Brief.](https://www.sciencedirect.com/science/article/pii/S2352340918315191)]

## Data Quality Check

You should demonstrate that you can read in your dataset(s) --- since we need proof of this, showing code is permitted or show code for the next steps. Quality check means providing answers to the following: How many variables and observations do you have? How many categorical vs numerical variables? Are there any missingness issues?

## Target Variable Analysis

A univariate analysis of the target variable. Identify and discuss potential issues (symmetry/unbalanced/skewness & missingness) and discuss potential solutions such as transformations.

## Misc

Students are encouraged to add any other information that they think would be useful to communicate about their data and their plan. Articulating a time line would be a good idea since fitting/training the models may take more time than expected (leave adequate time to train models and then analyze). 


